"""added gravatars

Revision ID: 1451bf57fb79
Revises: 2628e08ede5e
Create Date: 2015-08-04 14:30:19.620208

"""

# revision identifiers, used by Alembic.
revision = '1451bf57fb79'
down_revision = '2628e08ede5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
