"""ai to Game

Revision ID: 20d86532136c
Revises: 1f00b824911a
Create Date: 2015-09-15 15:00:36.747072

"""

# revision identifiers, used by Alembic.
revision = '20d86532136c'
down_revision = '1f00b824911a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ai', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ai')
    ### end Alembic commands ###
