"""added confirmation to users

Revision ID: 260130305d6c
Revises: 56721903f8e7
Create Date: 2015-08-03 13:58:11.842170

"""

# revision identifiers, used by Alembic.
revision = '260130305d6c'
down_revision = '56721903f8e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
