"""added gravatars

Revision ID: 38144bf8e233
Revises: 1451bf57fb79
Create Date: 2015-08-04 15:03:10.588323

"""

# revision identifiers, used by Alembic.
revision = '38144bf8e233'
down_revision = '1451bf57fb79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
