"""empty message

Revision ID: 43868430f957
Revises: None
Create Date: 2015-07-30 17:17:49.578696

"""

# revision identifiers, used by Alembic.
revision = '43868430f957'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
