"""working initial tests with postgres

Revision ID: 470cd21dc2f2
Revises: 43868430f957
Create Date: 2015-07-30 19:06:59.612739

"""

# revision identifiers, used by Alembic.
revision = '470cd21dc2f2'
down_revision = '43868430f957'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
