"""added game pid

Revision ID: 5651968fb60c
Revises: 4ee7c51f1bbd
Create Date: 2015-08-05 17:14:01.211795

"""

# revision identifiers, used by Alembic.
revision = '5651968fb60c'
down_revision = '4ee7c51f1bbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('proc_pid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'proc_pid')
    ### end Alembic commands ###
