"""created usernames, emails, passwords

Revision ID: 56721903f8e7
Revises: None
Create Date: 2015-08-03 12:24:53.777383

"""

# revision identifiers, used by Alembic.
revision = '56721903f8e7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
