"""added relationship between one game and many posts

Revision ID: 5833d5971a5e
Revises: 4cdd2cf993e3
Create Date: 2015-08-11 14:27:32.719874

"""

# revision identifiers, used by Alembic.
revision = '5833d5971a5e'
down_revision = '4cdd2cf993e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
