"""added fen string to user

Revision ID: c14b486d082
Revises: 5651968fb60c
Create Date: 2015-08-10 14:11:29.079190

"""

# revision identifiers, used by Alembic.
revision = 'c14b486d082'
down_revision = '5651968fb60c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('fen_state', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'fen_state')
    ### end Alembic commands ###
